name: Ohachat
version: '${version}'
main: com.outlook.furkan.dogan.dev.ohachat.OhaChat
api-version: 1.16
commands:
  ohaadmin:
    description: Admin command for channels.
  block:
    description: Block the player you don't want to see.
  unblock:
    description: Unblock someone you blocked.